require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'bin/**/*'     
    - 'db/**/*.rb'     
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'


Style/Documentation:
  Enabled: false
